### ISSUE TITLE
New system not able to unlock after running role

### ISSUE THREAD

**Issue by aheath1992** [linux-system-roles/nbde_client#150]
New system is unable to unlock after running the nbde_client role, after running the role get an all good from Ansible but upon reboot the system stops at the Luks encryption screen.

```
    - name: Import nbde_client role
      ansible.builtin.import_role:
        name: linux-system-roles.nbde_client
      vars:
        nbde_client_bindings:
          - device: "{{ root_disk | d('/dev/vda2') }}"
            encryption_password: "{{ current_password }}"
            servers: "{{ tang_servers }}"
```

![Screenshot from 2024-02-01 16-02-08](https://github.com/linux-system-roles/nbde_client/assets/44443152/a9e2122b-4b50-4f45-a80f-38e92883eb2e)
